on:
  push:
    branches:
      - zia
name: build gatsby
jobs:
  build_gatsby:
    name: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: "12.14.1"
      - run: npm install

      - name: gatsby build
        env:
          GH_API_KEY: ${{ secrets.PA_TOKEN }}
        run: yarn build

      - name: deploy
        uses: maxheld83/ghpages@v0.2.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GH_PAT: ${{ secrets.PA_TOKEN }}
          BUILD_DIR: "public/"
